export const ACTION__REQUEST_START = 'ACTION__REQUEST_START';

// login/logout related actions
export const ACTION__LOGIN = 'ACTION__LOGIN';
export const ACTION__LOGIN_SUCCESS = 'ACTION__LOGIN_SUCCESS';
export const ACTION__LOGIN_FAIL = 'ACTION__LOGIN_FAIL';
export const ACTION__LOGOUT = 'ACTION__LOGOUT';
export const ACTION__LOGOUT_SUCCESS = 'ACTION__LOGOUT_SUCCESS';
export const ACTION__LOGOUT_FAIL = 'ACTION__LOGOUT_FAIL';
